import { Restaurant, Category, MenuItem, Deal } from '../types/restaurant';
import { buildRestaurantTheme } from '../theme/theme';
import { Order, StatusUpdate } from '../types/order';
import { Address, User } from '../types/user';

// ─── Image helpers ──────────────────────────────────────────────────────────
// Centralized image source — easy to swap for real CDN URLs later
const IMG = {
  // Restaurant covers
  burgerCover: 'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=800',
  pizzaCover: 'https://images.unsplash.com/photo-1604382355076-af4b0eb60143?w=800',
  sushiCover: 'https://images.unsplash.com/photo-1553621042-f6e147245754?w=800',

  // Restaurant logos (placeholder colored images)
  burgerLogo: 'https://placehold.co/200x200/FF6B35/white?text=BB',
  pizzaLogo: 'https://placehold.co/200x200/D62828/white?text=NP',
  sushiLogo: 'https://placehold.co/200x200/1B4332/white?text=SK',

  // Menu item images
  burger1: 'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=400',
  burger2: 'https://images.unsplash.com/photo-1550547660-d9450f859349?w=400',
  burger3: 'https://images.unsplash.com/photo-1528735602780-2552fd46c7af?w=400',
  fries: 'https://images.unsplash.com/photo-1573080496219-bb080dd4f877?w=400',
  shake: 'https://images.unsplash.com/photo-1572490122747-3968b75cc699?w=400',
  onionRings: 'https://images.unsplash.com/photo-1639024471283-03518883512d?w=400',
  cokeFloat: 'https://images.unsplash.com/photo-1563227812-0ea4c22e6cc8?w=400',

  pizza1: 'https://images.unsplash.com/photo-1604382355076-af4b0eb60143?w=400',
  pizza2: 'https://images.unsplash.com/photo-1565299624946-b28f40a0ae38?w=400',
  pasta1: 'https://images.unsplash.com/photo-1621996346565-e3dbc646d9a9?w=400',
  salad: 'https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=400',
  tiramisu: 'https://images.unsplash.com/photo-1571877227200-a0d98ea607e9?w=400',
  garlic_bread: 'https://images.unsplash.com/photo-1619531038896-3b4f3d16dcfe?w=400',

  sushi1: 'https://images.unsplash.com/photo-1553621042-f6e147245754?w=400',
  sushi2: 'https://images.unsplash.com/photo-1617196034183-421b4040ed20?w=400',
  ramen: 'https://images.unsplash.com/photo-1569050467447-ce54b3bbc37d?w=400',
  miso: 'https://images.unsplash.com/photo-1547592166-23ac45744acd?w=400',
  gyoza: 'https://images.unsplash.com/photo-1496116218417-1a781b1c416c?w=400',
  matcha: 'https://images.unsplash.com/photo-1515823064-d6e0c04616a7?w=400',
};

// ─── Restaurant 1: Blazin' Burgers ─────────────────────────────────────────
const burgerCategories: Category[] = [
  { id: 'cat-bb-1', restaurantId: 'rest-1', name: 'Signature Burgers', sortOrder: 1, isAvailable: true },
  { id: 'cat-bb-2', restaurantId: 'rest-1', name: 'Chicken', sortOrder: 2, isAvailable: true },
  { id: 'cat-bb-3', restaurantId: 'rest-1', name: 'Sides & Fries', sortOrder: 3, isAvailable: true },
  { id: 'cat-bb-4', restaurantId: 'rest-1', name: 'Drinks & Shakes', sortOrder: 4, isAvailable: true },
];

const burgerMenuItems: MenuItem[] = [
  {
    id: 'item-bb-1',
    restaurantId: 'rest-1',
    categoryId: 'cat-bb-1',
    name: 'The Blazin\' Classic',
    description: 'Angus beef patty, aged cheddar, crispy lettuce, heirloom tomato, house pickles, signature Blazin\' sauce',
    image: IMG.burger1,
    basePrice: 950,
    calories: 720,
    prepTimeMinutes: 12,
    isAvailable: true,
    isPopular: true,
    isNew: false,
    isSpicy: false,
    isVegetarian: false,
    tags: ['best-seller', 'must-try'],
    sortOrder: 1,
    variantGroups: [
      {
        id: 'vg-1', name: 'Size', isRequired: true,
        variants: [
          { id: 'v-1', name: 'Regular', priceModifier: 0, isDefault: true },
          { id: 'v-2', name: 'Double Patty', priceModifier: 250, isDefault: false },
        ],
      },
    ],
    addOnGroups: [
      {
        id: 'aog-1', name: 'Add Extras', isRequired: false, maxSelections: 3,
        addOns: [
          { id: 'ao-1', name: 'Extra Cheese', price: 80, isAvailable: true },
          { id: 'ao-2', name: 'Caramelized Onions', price: 60, isAvailable: true },
          { id: 'ao-3', name: 'Jalapeños', price: 50, isAvailable: true },
          { id: 'ao-4', name: 'Avocado', price: 120, isAvailable: true },
        ],
      },
    ],
  },
  {
    id: 'item-bb-2',
    restaurantId: 'rest-1',
    categoryId: 'cat-bb-1',
    name: 'Smoky BBQ Stack',
    description: 'Smoked beef brisket, crispy bacon, BBQ sauce, pickled red onions, smoked gouda on a brioche bun',
    image: IMG.burger2,
    basePrice: 1150,
    calories: 890,
    prepTimeMinutes: 14,
    isAvailable: true,
    isPopular: true,
    isNew: false,
    isSpicy: false,
    isVegetarian: false,
    tags: ['popular'],
    sortOrder: 2,
    variantGroups: [],
    addOnGroups: [
      {
        id: 'aog-2', name: 'Extras', isRequired: false, maxSelections: 2,
        addOns: [
          { id: 'ao-5', name: 'Extra Bacon', price: 150, isAvailable: true },
          { id: 'ao-6', name: 'Fried Egg', price: 100, isAvailable: true },
        ],
      },
    ],
  },
  {
    id: 'item-bb-3',
    restaurantId: 'rest-1',
    categoryId: 'cat-bb-1',
    name: 'Habanero Heat',
    description: 'Spiced beef patty, habanero mayo, ghost pepper cheddar, pickled jalapeños, fresh chilli — for the bold',
    image: IMG.burger3,
    basePrice: 1050,
    calories: 760,
    prepTimeMinutes: 12,
    isAvailable: true,
    isPopular: false,
    isNew: true,
    isSpicy: true,
    isVegetarian: false,
    tags: ['spicy', 'new'],
    sortOrder: 3,
    variantGroups: [],
    addOnGroups: [],
  },
  {
    id: 'item-bb-4',
    restaurantId: 'rest-1',
    categoryId: 'cat-bb-2',
    name: 'Crispy Chicken Deluxe',
    description: 'Hand-breaded crispy chicken fillet, coleslaw, pickled cucumbers, honey-sriracha drizzle',
    image: IMG.burger1,
    basePrice: 880,
    calories: 680,
    prepTimeMinutes: 10,
    isAvailable: true,
    isPopular: true,
    isNew: false,
    isSpicy: false,
    isVegetarian: false,
    tags: ['popular', 'chicken'],
    sortOrder: 1,
    variantGroups: [
      {
        id: 'vg-2', name: 'Spice Level', isRequired: false,
        variants: [
          { id: 'v-3', name: 'Mild', priceModifier: 0, isDefault: true },
          { id: 'v-4', name: 'Medium', priceModifier: 0, isDefault: false },
          { id: 'v-5', name: 'Hot', priceModifier: 0, isDefault: false },
        ],
      },
    ],
    addOnGroups: [],
  },
  {
    id: 'item-bb-5',
    restaurantId: 'rest-1',
    categoryId: 'cat-bb-3',
    name: 'Seasoned Fries',
    description: 'Golden-cut potatoes tossed in our signature spice blend, served with dipping sauce',
    image: IMG.fries,
    basePrice: 320,
    calories: 380,
    prepTimeMinutes: 8,
    isAvailable: true,
    isPopular: true,
    isNew: false,
    isSpicy: false,
    isVegetarian: true,
    tags: ['sides'],
    sortOrder: 1,
    variantGroups: [
      {
        id: 'vg-3', name: 'Size', isRequired: true,
        variants: [
          { id: 'v-6', name: 'Regular', priceModifier: 0, isDefault: true },
          { id: 'v-7', name: 'Large', priceModifier: 120, isDefault: false },
        ],
      },
    ],
    addOnGroups: [],
  },
  {
    id: 'item-bb-6',
    restaurantId: 'rest-1',
    categoryId: 'cat-bb-3',
    name: 'Onion Rings',
    description: 'Thick-cut onion rings in a seasoned beer batter, served with chipotle dip',
    image: IMG.onionRings,
    basePrice: 360,
    calories: 420,
    prepTimeMinutes: 8,
    isAvailable: true,
    isPopular: false,
    isNew: false,
    isSpicy: false,
    isVegetarian: true,
    tags: [],
    sortOrder: 2,
    variantGroups: [],
    addOnGroups: [],
  },
  {
    id: 'item-bb-7',
    restaurantId: 'rest-1',
    categoryId: 'cat-bb-4',
    name: 'Thick Milkshake',
    description: 'Rich, hand-spun milkshake made with real ice cream',
    image: IMG.shake,
    basePrice: 490,
    calories: 520,
    prepTimeMinutes: 5,
    isAvailable: true,
    isPopular: true,
    isNew: false,
    isSpicy: false,
    isVegetarian: true,
    tags: ['drink'],
    sortOrder: 1,
    variantGroups: [
      {
        id: 'vg-4', name: 'Flavour', isRequired: true,
        variants: [
          { id: 'v-8', name: 'Chocolate', priceModifier: 0, isDefault: true },
          { id: 'v-9', name: 'Vanilla', priceModifier: 0, isDefault: false },
          { id: 'v-10', name: 'Strawberry', priceModifier: 0, isDefault: false },
          { id: 'v-11', name: 'Salted Caramel', priceModifier: 50, isDefault: false },
        ],
      },
    ],
    addOnGroups: [],
  },
  {
    id: 'item-bb-8',
    restaurantId: 'rest-1',
    categoryId: 'cat-bb-4',
    name: 'Cola Float',
    description: 'Chilled cola topped with a scoop of vanilla ice cream',
    image: IMG.cokeFloat,
    basePrice: 280,
    calories: 310,
    prepTimeMinutes: 3,
    isAvailable: true,
    isPopular: false,
    isNew: false,
    isSpicy: false,
    isVegetarian: true,
    tags: [],
    sortOrder: 2,
    variantGroups: [],
    addOnGroups: [],
  },
];

const burgerDeals: Deal[] = [
  {
    id: 'deal-bb-1',
    restaurantId: 'rest-1',
    title: 'Burger Combo Deal',
    description: 'Any Signature Burger + Seasoned Fries + Milkshake for the price of two',
    image: IMG.burgerCover,
    type: 'percentage',
    value: 20,
    minOrderAmount: 1500,
    couponCode: 'BLAZIN20',
    validFrom: '2026-01-01',
    validTo: '2026-12-31',
    isActive: true,
  },
  {
    id: 'deal-bb-2',
    restaurantId: 'rest-1',
    title: 'Free Delivery Friday',
    description: 'Enjoy free delivery every Friday on orders above PKR 800',
    type: 'free_delivery',
    value: 0,
    minOrderAmount: 800,
    validFrom: '2026-01-01',
    validTo: '2026-12-31',
    isActive: true,
  },
];

// ─── Restaurant 2: Napoli Pizza Co. ────────────────────────────────────────
const pizzaCategories: Category[] = [
  { id: 'cat-np-1', restaurantId: 'rest-2', name: 'Classic Pizzas', sortOrder: 1, isAvailable: true },
  { id: 'cat-np-2', restaurantId: 'rest-2', name: 'Gourmet Pizzas', sortOrder: 2, isAvailable: true },
  { id: 'cat-np-3', restaurantId: 'rest-2', name: 'Pasta', sortOrder: 3, isAvailable: true },
  { id: 'cat-np-4', restaurantId: 'rest-2', name: 'Starters', sortOrder: 4, isAvailable: true },
  { id: 'cat-np-5', restaurantId: 'rest-2', name: 'Desserts', sortOrder: 5, isAvailable: true },
];

const pizzaMenuItems: MenuItem[] = [
  {
    id: 'item-np-1',
    restaurantId: 'rest-2',
    categoryId: 'cat-np-1',
    name: 'Margherita Classica',
    description: 'San Marzano tomatoes, fresh fior di latte mozzarella, fresh basil, extra-virgin olive oil on our 72-hour fermented dough',
    image: IMG.pizza1,
    basePrice: 1200,
    calories: 840,
    prepTimeMinutes: 18,
    isAvailable: true,
    isPopular: true,
    isNew: false,
    isSpicy: false,
    isVegetarian: true,
    tags: ['vegetarian', 'classic'],
    sortOrder: 1,
    variantGroups: [
      {
        id: 'vg-p1', name: 'Size', isRequired: true,
        variants: [
          { id: 'v-p1', name: '9"', priceModifier: 0, isDefault: true },
          { id: 'v-p2', name: '12"', priceModifier: 350, isDefault: false },
          { id: 'v-p3', name: '15"', priceModifier: 650, isDefault: false },
        ],
      },
      {
        id: 'vg-p2', name: 'Crust', isRequired: true,
        variants: [
          { id: 'v-p4', name: 'Thin & Crispy', priceModifier: 0, isDefault: true },
          { id: 'v-p5', name: 'Classic Hand-Tossed', priceModifier: 0, isDefault: false },
          { id: 'v-p6', name: 'Stuffed Crust', priceModifier: 200, isDefault: false },
        ],
      },
    ],
    addOnGroups: [
      {
        id: 'aog-p1', name: 'Extra Toppings', isRequired: false, maxSelections: 4,
        addOns: [
          { id: 'ao-p1', name: 'Extra Mozzarella', price: 150, isAvailable: true },
          { id: 'ao-p2', name: 'Mushrooms', price: 100, isAvailable: true },
          { id: 'ao-p3', name: 'Black Olives', price: 100, isAvailable: true },
          { id: 'ao-p4', name: 'Sun-dried Tomatoes', price: 120, isAvailable: true },
        ],
      },
    ],
  },
  {
    id: 'item-np-2',
    restaurantId: 'rest-2',
    categoryId: 'cat-np-2',
    name: 'Truffle & Prosciutto',
    description: 'Black truffle cream base, prosciutto crudo, rocket leaves, shaved parmigiano, truffle oil finish',
    image: IMG.pizza2,
    basePrice: 2200,
    calories: 960,
    prepTimeMinutes: 20,
    isAvailable: true,
    isPopular: true,
    isNew: false,
    isSpicy: false,
    isVegetarian: false,
    tags: ['gourmet', 'premium'],
    sortOrder: 1,
    variantGroups: [
      {
        id: 'vg-p3', name: 'Size', isRequired: true,
        variants: [
          { id: 'v-p7', name: '9"', priceModifier: 0, isDefault: true },
          { id: 'v-p8', name: '12"', priceModifier: 400, isDefault: false },
        ],
      },
    ],
    addOnGroups: [],
  },
  {
    id: 'item-np-3',
    restaurantId: 'rest-2',
    categoryId: 'cat-np-3',
    name: 'Cacio e Pepe',
    description: 'Tonnarelli pasta, Pecorino Romano, Parmigiano-Reggiano, freshly cracked black pepper — a Roman classic',
    image: IMG.pasta1,
    basePrice: 980,
    calories: 720,
    prepTimeMinutes: 15,
    isAvailable: true,
    isPopular: true,
    isNew: false,
    isSpicy: false,
    isVegetarian: true,
    tags: ['pasta', 'vegetarian'],
    sortOrder: 1,
    variantGroups: [],
    addOnGroups: [],
  },
  {
    id: 'item-np-4',
    restaurantId: 'rest-2',
    categoryId: 'cat-np-4',
    name: 'Insalata Mista',
    description: 'Mixed greens, cherry tomatoes, cucumber, red onion, Kalamata olives, house Italian dressing',
    image: IMG.salad,
    basePrice: 680,
    calories: 280,
    prepTimeMinutes: 8,
    isAvailable: true,
    isPopular: false,
    isNew: false,
    isSpicy: false,
    isVegetarian: true,
    tags: ['salad', 'healthy'],
    sortOrder: 1,
    variantGroups: [],
    addOnGroups: [],
  },
  {
    id: 'item-np-5',
    restaurantId: 'rest-2',
    categoryId: 'cat-np-4',
    name: 'Garlic Focaccia',
    description: 'Freshly baked rosemary focaccia with roasted garlic butter and sea salt',
    image: IMG.garlic_bread,
    basePrice: 420,
    calories: 380,
    prepTimeMinutes: 10,
    isAvailable: true,
    isPopular: true,
    isNew: false,
    isSpicy: false,
    isVegetarian: true,
    tags: ['bread', 'starter'],
    sortOrder: 2,
    variantGroups: [],
    addOnGroups: [],
  },
  {
    id: 'item-np-6',
    restaurantId: 'rest-2',
    categoryId: 'cat-np-5',
    name: 'Tiramisu',
    description: 'Classic Italian tiramisu — Savoiardi biscuits, espresso, mascarpone cream, cocoa powder',
    image: IMG.tiramisu,
    basePrice: 620,
    calories: 480,
    prepTimeMinutes: 5,
    isAvailable: true,
    isPopular: true,
    isNew: false,
    isSpicy: false,
    isVegetarian: true,
    tags: ['dessert', 'must-try'],
    sortOrder: 1,
    variantGroups: [],
    addOnGroups: [],
  },
];

const pizzaDeals: Deal[] = [
  {
    id: 'deal-np-1',
    restaurantId: 'rest-2',
    title: 'Famiglia Bundle',
    description: 'Two 12" pizzas + Garlic Focaccia + Two soft drinks — perfect for sharing',
    image: IMG.pizzaCover,
    type: 'fixed',
    value: 500,
    minOrderAmount: 3000,
    couponCode: 'NAPOLI15',
    validFrom: '2026-01-01',
    validTo: '2026-12-31',
    isActive: true,
  },
  {
    id: 'deal-np-2',
    restaurantId: 'rest-2',
    title: 'Lunch Special',
    description: 'Any classic pizza + salad + soft drink — Monday to Friday 12pm–3pm',
    type: 'percentage',
    value: 15,
    minOrderAmount: 1500,
    validFrom: '2026-01-01',
    validTo: '2026-12-31',
    isActive: true,
  },
];

// ─── Restaurant 3: Sakura Kitchen ──────────────────────────────────────────
const sushiCategories: Category[] = [
  { id: 'cat-sk-1', restaurantId: 'rest-3', name: 'Sushi & Maki', sortOrder: 1, isAvailable: true },
  { id: 'cat-sk-2', restaurantId: 'rest-3', name: 'Premium Rolls', sortOrder: 2, isAvailable: true },
  { id: 'cat-sk-3', restaurantId: 'rest-3', name: 'Ramen & Soups', sortOrder: 3, isAvailable: true },
  { id: 'cat-sk-4', restaurantId: 'rest-3', name: 'Starters', sortOrder: 4, isAvailable: true },
  { id: 'cat-sk-5', restaurantId: 'rest-3', name: 'Drinks', sortOrder: 5, isAvailable: true },
];

const sushiMenuItems: MenuItem[] = [
  {
    id: 'item-sk-1',
    restaurantId: 'rest-3',
    categoryId: 'cat-sk-1',
    name: 'Salmon Nigiri',
    description: 'Sashimi-grade Norwegian salmon over seasoned sushi rice, served with pickled ginger and wasabi',
    image: IMG.sushi1,
    basePrice: 780,
    calories: 240,
    prepTimeMinutes: 10,
    isAvailable: true,
    isPopular: true,
    isNew: false,
    isSpicy: false,
    isVegetarian: false,
    tags: ['sushi', 'popular'],
    sortOrder: 1,
    variantGroups: [
      {
        id: 'vg-s1', name: 'Pieces', isRequired: true,
        variants: [
          { id: 'v-s1', name: '4 pcs', priceModifier: 0, isDefault: true },
          { id: 'v-s2', name: '8 pcs', priceModifier: 680, isDefault: false },
        ],
      },
    ],
    addOnGroups: [],
  },
  {
    id: 'item-sk-2',
    restaurantId: 'rest-3',
    categoryId: 'cat-sk-2',
    name: 'Dragon Roll',
    description: 'Tempura prawn inside, topped with fresh avocado, eel sauce, and tobiko',
    image: IMG.sushi2,
    basePrice: 1480,
    calories: 560,
    prepTimeMinutes: 15,
    isAvailable: true,
    isPopular: true,
    isNew: false,
    isSpicy: false,
    isVegetarian: false,
    tags: ['premium', 'popular'],
    sortOrder: 1,
    variantGroups: [],
    addOnGroups: [
      {
        id: 'aog-s1', name: 'Add On', isRequired: false, maxSelections: 2,
        addOns: [
          { id: 'ao-s1', name: 'Extra Eel Sauce', price: 80, isAvailable: true },
          { id: 'ao-s2', name: 'Spicy Mayo', price: 80, isAvailable: true },
        ],
      },
    ],
  },
  {
    id: 'item-sk-3',
    restaurantId: 'rest-3',
    categoryId: 'cat-sk-3',
    name: 'Tonkotsu Ramen',
    description: '12-hour pork bone broth, chashu pork belly, soft-boiled marinated egg, nori, green onions, bamboo shoots',
    image: IMG.ramen,
    basePrice: 1350,
    calories: 780,
    prepTimeMinutes: 20,
    isAvailable: true,
    isPopular: true,
    isNew: false,
    isSpicy: false,
    isVegetarian: false,
    tags: ['ramen', 'popular'],
    sortOrder: 1,
    variantGroups: [
      {
        id: 'vg-s2', name: 'Broth Richness', isRequired: false,
        variants: [
          { id: 'v-s3', name: 'Classic', priceModifier: 0, isDefault: true },
          { id: 'v-s4', name: 'Extra Rich', priceModifier: 0, isDefault: false },
        ],
      },
    ],
    addOnGroups: [
      {
        id: 'aog-s2', name: 'Add Extra', isRequired: false, maxSelections: 3,
        addOns: [
          { id: 'ao-s3', name: 'Extra Chashu', price: 200, isAvailable: true },
          { id: 'ao-s4', name: 'Extra Egg', price: 120, isAvailable: true },
          { id: 'ao-s5', name: 'Corn', price: 80, isAvailable: true },
        ],
      },
    ],
  },
  {
    id: 'item-sk-4',
    restaurantId: 'rest-3',
    categoryId: 'cat-sk-4',
    name: 'Miso Soup',
    description: 'Authentic dashi broth, silken tofu, wakame seaweed, green onions',
    image: IMG.miso,
    basePrice: 280,
    calories: 90,
    prepTimeMinutes: 5,
    isAvailable: true,
    isPopular: false,
    isNew: false,
    isSpicy: false,
    isVegetarian: true,
    tags: ['soup', 'starter'],
    sortOrder: 2,
    variantGroups: [],
    addOnGroups: [],
  },
  {
    id: 'item-sk-5',
    restaurantId: 'rest-3',
    categoryId: 'cat-sk-4',
    name: 'Chicken Gyoza',
    description: 'Pan-fried Japanese dumplings filled with chicken and cabbage, served with ponzu dipping sauce',
    image: IMG.gyoza,
    basePrice: 680,
    calories: 340,
    prepTimeMinutes: 12,
    isAvailable: true,
    isPopular: true,
    isNew: false,
    isSpicy: false,
    isVegetarian: false,
    tags: ['gyoza', 'starter'],
    sortOrder: 1,
    variantGroups: [
      {
        id: 'vg-s3', name: 'Pieces', isRequired: true,
        variants: [
          { id: 'v-s5', name: '5 pcs', priceModifier: 0, isDefault: true },
          { id: 'v-s6', name: '10 pcs', priceModifier: 600, isDefault: false },
        ],
      },
    ],
    addOnGroups: [],
  },
  {
    id: 'item-sk-6',
    restaurantId: 'rest-3',
    categoryId: 'cat-sk-5',
    name: 'Matcha Latte',
    description: 'Ceremonial grade matcha from Uji, steamed oat milk, lightly sweetened',
    image: IMG.matcha,
    basePrice: 480,
    calories: 180,
    prepTimeMinutes: 5,
    isAvailable: true,
    isPopular: true,
    isNew: false,
    isSpicy: false,
    isVegetarian: true,
    tags: ['drink', 'popular'],
    sortOrder: 1,
    variantGroups: [
      {
        id: 'vg-s4', name: 'Temperature', isRequired: true,
        variants: [
          { id: 'v-s7', name: 'Hot', priceModifier: 0, isDefault: true },
          { id: 'v-s8', name: 'Iced', priceModifier: 50, isDefault: false },
        ],
      },
    ],
    addOnGroups: [],
  },
];

const sushiDeals: Deal[] = [
  {
    id: 'deal-sk-1',
    restaurantId: 'rest-3',
    title: 'Sushi & Ramen Set',
    description: 'Dragon Roll + Tonkotsu Ramen + Matcha Latte — complete Japanese experience',
    image: IMG.sushiCover,
    type: 'percentage',
    value: 18,
    minOrderAmount: 2500,
    couponCode: 'SAKURA18',
    validFrom: '2026-01-01',
    validTo: '2026-12-31',
    isActive: true,
  },
  {
    id: 'deal-sk-2',
    restaurantId: 'rest-3',
    title: 'Weekend Bento Special',
    description: 'Any premium roll + miso soup + gyoza with free delivery on weekends',
    type: 'free_delivery',
    value: 0,
    minOrderAmount: 2000,
    validFrom: '2026-01-01',
    validTo: '2026-12-31',
    isActive: true,
  },
];

// ─── Full restaurant objects ────────────────────────────────────────────────
export const DUMMY_RESTAURANTS: Restaurant[] = [
  {
    id: 'rest-1',
    name: "Blazin' Burgers",
    slug: 'blazin-burgers',
    logo: IMG.burgerLogo,
    coverImage: IMG.burgerCover,
    description: "Handcrafted burgers made with premium Angus beef, house-made sauces, and fresh-baked brioche buns. Every bite is a flavour explosion.",
    address: 'Shop 14, Centaurus Mall, Islamabad',
    city: 'Islamabad',
    phone: '+92-51-111-222-333',
    email: 'hello@blazinburgers.pk',
    primaryColor: '#FF6B35',
    theme: buildRestaurantTheme('#FF6B35', false),
    openingHours: {
      monday: { isOpen: true, openTime: '11:00', closeTime: '23:00' },
      tuesday: { isOpen: true, openTime: '11:00', closeTime: '23:00' },
      wednesday: { isOpen: true, openTime: '11:00', closeTime: '23:00' },
      thursday: { isOpen: true, openTime: '11:00', closeTime: '23:00' },
      friday: { isOpen: true, openTime: '11:00', closeTime: '00:00' },
      saturday: { isOpen: true, openTime: '10:00', closeTime: '00:00' },
      sunday: { isOpen: true, openTime: '10:00', closeTime: '23:00' },
    },
    isOpen: true,
    estimatedDeliveryTime: '25–35 min',
    currency: 'PKR',
    taxRate: 0.05,
    deliveryFee: 150,
    minimumOrderAmount: 500,
    rating: 4.7,
    reviewCount: 1842,
    categories: burgerCategories,
    menuItems: burgerMenuItems,
    deals: burgerDeals,
    isActive: true,
    distance: 1.2,
    tags: ['burgers', 'fast-food', 'american'],
  },
  {
    id: 'rest-2',
    name: 'Napoli Pizza Co.',
    slug: 'napoli-pizza-co',
    logo: IMG.pizzaLogo,
    coverImage: IMG.pizzaCover,
    description: 'Authentic Neapolitan pizza crafted with imported Italian ingredients, 72-hour fermented dough, and baked in a wood-fired oven.',
    address: 'F-7/2, Jinnah Super Market, Islamabad',
    city: 'Islamabad',
    phone: '+92-51-444-555-666',
    email: 'ciao@napolipizza.pk',
    primaryColor: '#D62828',
    theme: buildRestaurantTheme('#D62828', false),
    openingHours: {
      monday: { isOpen: false, openTime: '', closeTime: '' },
      tuesday: { isOpen: true, openTime: '12:00', closeTime: '23:00' },
      wednesday: { isOpen: true, openTime: '12:00', closeTime: '23:00' },
      thursday: { isOpen: true, openTime: '12:00', closeTime: '23:00' },
      friday: { isOpen: true, openTime: '12:00', closeTime: '00:00' },
      saturday: { isOpen: true, openTime: '11:00', closeTime: '00:00' },
      sunday: { isOpen: true, openTime: '11:00', closeTime: '23:00' },
    },
    isOpen: true,
    estimatedDeliveryTime: '30–45 min',
    currency: 'PKR',
    taxRate: 0.05,
    deliveryFee: 200,
    minimumOrderAmount: 800,
    rating: 4.9,
    reviewCount: 3201,
    categories: pizzaCategories,
    menuItems: pizzaMenuItems,
    deals: pizzaDeals,
    isActive: true,
    distance: 2.8,
    tags: ['pizza', 'italian', 'pasta'],
  },
  {
    id: 'rest-3',
    name: 'Sakura Kitchen',
    slug: 'sakura-kitchen',
    logo: IMG.sushiLogo,
    coverImage: IMG.sushiCover,
    description: 'A contemporary Japanese kitchen offering omakase-inspired sushi, handcrafted ramen, and traditional izakaya dishes.',
    address: 'Plot 8, Kohsar Market, F-6, Islamabad',
    city: 'Islamabad',
    phone: '+92-51-777-888-999',
    email: 'konnichiwa@sakurakitchen.pk',
    primaryColor: '#1B4332',
    theme: buildRestaurantTheme('#1B4332', false),
    openingHours: {
      monday: { isOpen: true, openTime: '12:00', closeTime: '22:30' },
      tuesday: { isOpen: true, openTime: '12:00', closeTime: '22:30' },
      wednesday: { isOpen: true, openTime: '12:00', closeTime: '22:30' },
      thursday: { isOpen: true, openTime: '12:00', closeTime: '22:30' },
      friday: { isOpen: true, openTime: '12:00', closeTime: '23:30' },
      saturday: { isOpen: true, openTime: '11:00', closeTime: '23:30' },
      sunday: { isOpen: true, openTime: '11:00', closeTime: '22:00' },
    },
    isOpen: true,
    estimatedDeliveryTime: '35–50 min',
    currency: 'PKR',
    taxRate: 0.05,
    deliveryFee: 250,
    minimumOrderAmount: 1000,
    rating: 4.8,
    reviewCount: 987,
    categories: sushiCategories,
    menuItems: sushiMenuItems,
    deals: sushiDeals,
    isActive: true,
    distance: 3.5,
    tags: ['japanese', 'sushi', 'ramen'],
  },
];

// ─── Dummy user ─────────────────────────────────────────────────────────────
export const DUMMY_USER: User = {
  id: 'user-1',
  fullName: 'Ahmed Raza',
  email: 'ahmed.raza@gmail.com',
  phone: '+92-300-1234567',
  isEmailVerified: true,
  isPhoneVerified: false,
  createdAt: '2025-08-01T10:00:00Z',
};

// ─── Dummy addresses ─────────────────────────────────────────────────────────
export const DUMMY_ADDRESSES: Address[] = [
  {
    id: 'addr-1',
    userId: 'user-1',
    label: 'home',
    streetAddress: 'House 12, Street 5, F-8/2',
    city: 'Islamabad',
    state: 'Islamabad Capital Territory',
    zipCode: '44000',
    country: 'Pakistan',
    coordinates: { latitude: 33.7215, longitude: 73.0433 },
    instructions: 'Green gate, ring the bell twice',
    isDefault: true,
    createdAt: '2025-08-01T10:00:00Z',
  },
  {
    id: 'addr-2',
    userId: 'user-1',
    label: 'work',
    streetAddress: 'Office 4B, Blue Area, Jinnah Avenue',
    city: 'Islamabad',
    state: 'Islamabad Capital Territory',
    zipCode: '44000',
    country: 'Pakistan',
    isDefault: false,
    createdAt: '2025-08-10T10:00:00Z',
  },
];

// ─── Dummy orders ─────────────────────────────────────────────────────────
export const DUMMY_ORDERS: Order[] = [
  {
    id: 'order-1',
    orderNumber: 'BB-20260901-001',
    restaurantId: 'rest-1',
    restaurantName: "Blazin' Burgers",
    restaurantLogo: IMG.burgerLogo,
    userId: 'user-1',
    items: [
      {
        id: 'ci-1',
        restaurantId: 'rest-1',
        menuItemId: 'item-bb-1',
        name: "The Blazin' Classic",
        image: IMG.burger1,
        basePrice: 950,
        selectedVariants: [{ groupId: 'vg-1', groupName: 'Size', variantId: 'v-2', variantName: 'Double Patty', priceModifier: 250 }],
        selectedAddOns: [{ groupId: 'aog-1', groupName: 'Add Extras', addOnId: 'ao-1', addOnName: 'Extra Cheese', price: 80 }],
        quantity: 2,
        notes: 'No pickles please',
        unitPrice: 1280,
        totalPrice: 2560,
      },
      {
        id: 'ci-2',
        restaurantId: 'rest-1',
        menuItemId: 'item-bb-5',
        name: 'Seasoned Fries',
        image: IMG.fries,
        basePrice: 320,
        selectedVariants: [{ groupId: 'vg-3', groupName: 'Size', variantId: 'v-7', variantName: 'Large', priceModifier: 120 }],
        selectedAddOns: [],
        quantity: 1,
        unitPrice: 440,
        totalPrice: 440,
      },
    ],
    type: 'delivery',
    deliveryAddress: DUMMY_ADDRESSES[0],
    paymentMethod: 'cash',
    paymentStatus: 'pending',
    subtotal: 3000,
    taxAmount: 150,
    taxRate: 0.05,
    deliveryFee: 150,
    discountAmount: 0,
    total: 3300,
    status: 'out_for_delivery',
    statusHistory: [
      { status: 'pending', timestamp: '2026-09-01T10:00:00Z' },
      { status: 'confirmed', timestamp: '2026-09-01T10:05:00Z' },
      { status: 'preparing', timestamp: '2026-09-01T10:08:00Z' },
      { status: 'ready', timestamp: '2026-09-01T10:25:00Z' },
      { status: 'out_for_delivery', timestamp: '2026-09-01T10:30:00Z' },
    ],
    estimatedDeliveryTime: '25–35 min',
    isRated: false,
    clientOrderRequestId: 'req-001',
    createdAt: '2026-09-01T10:00:00Z',
    updatedAt: '2026-09-01T10:30:00Z',
  },
  {
    id: 'order-2',
    orderNumber: 'NP-20260830-042',
    restaurantId: 'rest-2',
    restaurantName: 'Napoli Pizza Co.',
    restaurantLogo: IMG.pizzaLogo,
    userId: 'user-1',
    items: [
      {
        id: 'ci-3',
        restaurantId: 'rest-2',
        menuItemId: 'item-np-1',
        name: 'Margherita Classica',
        image: IMG.pizza1,
        basePrice: 1200,
        selectedVariants: [
          { groupId: 'vg-p1', groupName: 'Size', variantId: 'v-p2', variantName: '12"', priceModifier: 350 },
          { groupId: 'vg-p2', groupName: 'Crust', variantId: 'v-p5', variantName: 'Classic Hand-Tossed', priceModifier: 0 },
        ],
        selectedAddOns: [],
        quantity: 1,
        unitPrice: 1550,
        totalPrice: 1550,
      },
    ],
    type: 'delivery',
    deliveryAddress: DUMMY_ADDRESSES[0],
    paymentMethod: 'cash',
    paymentStatus: 'paid',
    subtotal: 1550,
    taxAmount: 77.5,
    taxRate: 0.05,
    deliveryFee: 200,
    discountAmount: 232.5,
    total: 1595,
    coupon: { code: 'NAPOLI15', dealId: 'deal-np-2', discountAmount: 232.5, description: '15% off' },
    status: 'delivered',
    statusHistory: [
      { status: 'pending', timestamp: '2026-08-30T14:00:00Z' },
      { status: 'confirmed', timestamp: '2026-08-30T14:05:00Z' },
      { status: 'preparing', timestamp: '2026-08-30T14:08:00Z' },
      { status: 'ready', timestamp: '2026-08-30T14:35:00Z' },
      { status: 'out_for_delivery', timestamp: '2026-08-30T14:40:00Z' },
      { status: 'delivered', timestamp: '2026-08-30T15:10:00Z' },
    ],
    isRated: true,
    rating: 5,
    review: 'Best pizza in Islamabad, always fresh and delicious!',
    clientOrderRequestId: 'req-002',
    createdAt: '2026-08-30T14:00:00Z',
    updatedAt: '2026-08-30T15:10:00Z',
  },
];

// ─── Helper functions ────────────────────────────────────────────────────────
export function getRestaurantById(id: string): Restaurant | undefined {
  return DUMMY_RESTAURANTS.find(r => r.id === id);
}

export function getMenuItemById(restaurantId: string, itemId: string): MenuItem | undefined {
  const restaurant = getRestaurantById(restaurantId);
  return restaurant?.menuItems.find(i => i.id === itemId);
}

export function getItemsByCategory(restaurantId: string, categoryId: string): MenuItem[] {
  const restaurant = getRestaurantById(restaurantId);
  return restaurant?.menuItems.filter(i => i.categoryId === categoryId && i.isAvailable) ?? [];
}

export function searchMenuItems(restaurantId: string, query: string): MenuItem[] {
  const restaurant = getRestaurantById(restaurantId);
  if (!restaurant || !query.trim()) return [];
  const q = query.toLowerCase();
  return restaurant.menuItems.filter(
    item =>
      item.isAvailable &&
      (item.name.toLowerCase().includes(q) ||
        item.description.toLowerCase().includes(q) ||
        item.tags.some(t => t.toLowerCase().includes(q)))
  );
}
