export const LIMITS = {
  // Auth
  MIN_NAME_LENGTH: 3,
  MAX_NAME_LENGTH: 50,
  MIN_PASSWORD_LENGTH: 8,
  MAX_PASSWORD_LENGTH: 128,
  OTP_LENGTH: 6,

  // Cart
  MAX_CART_ITEMS: 50,
  MAX_ITEM_QUANTITY: 20,

  // Content
  MAX_REVIEW_CHARS: 500,
  MAX_ORDER_NOTE_CHARS: 500,
  MAX_ITEM_NOTE_CHARS: 200,
  MAX_ADDRESS_LABEL_CHARS: 30,
  MAX_ADDRESS_NOTE_CHARS: 200,
} as const;
