/**
 * All user-facing strings in one place for easy localization.
 * Replace with i18n library when multi-language support is added.
 */
export const strings = {
  // App
  appName: 'FoodieApp',

  // Auth
  auth: {
    welcomeTitle: 'Welcome back',
    welcomeSubtitle: 'Sign in to continue your order',
    loginTitle: 'Sign In',
    registerTitle: 'Create Account',
    registerSubtitle: 'Join us for great food delivered fast',
    forgotPasswordTitle: 'Reset Password',
    forgotPasswordSubtitle: "Enter your email and we'll send a reset link",
    resetPasswordTitle: 'New Password',
    verifyEmailTitle: 'Verify Email',
    verifyEmailSubtitle: "We've sent a 6-digit code to",
    fullName: 'Full Name',
    email: 'Email',
    phone: 'Phone Number',
    password: 'Password',
    confirmPassword: 'Confirm Password',
    signIn: 'Sign In',
    signUp: 'Create Account',
    forgotPassword: 'Forgot password?',
    dontHaveAccount: "Don't have an account?",
    alreadyHaveAccount: 'Already have an account?',
    orContinueWith: 'or continue with',
    sendOtp: 'Send Code',
    verifyOtp: 'Verify',
    resendCode: 'Resend code',
    resendIn: 'Resend in',
    resetPassword: 'Reset Password',
    logout: 'Log Out',
    logoutConfirmTitle: 'Log Out',
    logoutConfirmMessage: 'Are you sure you want to log out?',
  },

  // Restaurant
  restaurant: {
    selectRestaurant: 'Select Restaurant',
    searchPlaceholder: 'Search restaurants...',
    scanQR: 'Scan QR Code',
    switchRestaurant: 'Switch Restaurant',
    switchConfirmTitle: 'Switch Restaurant?',
    switchConfirmMessage:
      'Switching restaurants will clear your current cart. Are you sure?',
    loading: 'Loading restaurant...',
    open: 'Open',
    closed: 'Closed',
    minOrder: 'Min. order',
    deliveryFee: 'Delivery fee',
    estimatedTime: 'Est. time',
    free: 'Free',
    noRestaurantsFound: 'No restaurants found',
    tryDifferentSearch: 'Try a different search term',
    invalidQR: 'Invalid QR Code',
    inactiveRestaurant: 'This restaurant is currently unavailable',
    qrPermissionTitle: 'Camera Permission',
    qrPermissionMessage: 'Please allow camera access to scan QR codes',
  },

  // Menu
  menu: {
    searchPlaceholder: 'Search menu...',
    allCategories: 'All',
    addToCart: 'Add to Cart',
    updateCart: 'Update Cart',
    outOfStock: 'Out of Stock',
    popular: 'Popular',
    new: 'New',
    spicy: 'Spicy',
    vegetarian: 'Vegetarian',
    calories: 'cal',
    prepTime: 'min',
    noItemsFound: 'No items found',
    variants: 'Choose a variant',
    addOns: 'Add extras',
    notes: 'Special instructions',
    notesPlaceholder: 'E.g. no onions, extra sauce...',
    relatedItems: 'You might also like',
    required: 'Required',
    optional: 'Optional',
    selectOne: 'Select one',
    selectUpTo: 'Select up to',
  },

  // Cart
  cart: {
    title: 'Your Cart',
    empty: 'Your cart is empty',
    emptySubtitle: 'Add items from the menu to get started',
    subtotal: 'Subtotal',
    tax: 'Tax',
    deliveryFee: 'Delivery fee',
    discount: 'Discount',
    total: 'Total',
    applyCoupon: 'Apply coupon',
    couponPlaceholder: 'Enter coupon code',
    apply: 'Apply',
    remove: 'Remove',
    proceedToCheckout: 'Proceed to Checkout',
    minimumOrder: 'Minimum order is',
    clearCart: 'Clear Cart',
    clearCartConfirm: 'Remove all items from your cart?',
    swipeToRemove: 'Swipe to remove',
  },

  // Checkout
  checkout: {
    title: 'Checkout',
    delivery: 'Delivery',
    takeaway: 'Takeaway',
    deliveryAddress: 'Delivery Address',
    addAddress: 'Add Address',
    changeAddress: 'Change',
    paymentMethod: 'Payment Method',
    orderNotes: 'Order Notes',
    orderNotesPlaceholder: 'Any special instructions for your order...',
    placeOrder: 'Place Order',
    orderSummary: 'Order Summary',
    processing: 'Placing your order...',
    cash: 'Cash on Delivery',
    card: 'Credit / Debit Card',
    wallet: 'Digital Wallet',
    noAddress: 'Please add a delivery address',
  },

  // Order
  order: {
    title: 'Orders',
    active: 'Active',
    history: 'History',
    track: 'Track Order',
    reorder: 'Reorder',
    cancel: 'Cancel Order',
    cancelConfirmTitle: 'Cancel Order?',
    cancelConfirmMessage: 'Are you sure you want to cancel this order?',
    cancellationReason: 'Reason for cancellation',
    orderNumber: 'Order #',
    estimatedTime: 'Estimated time',
    noActiveOrders: 'No active orders',
    noOrderHistory: 'No order history',
    startOrdering: 'Start ordering to see your history here',
    status: {
      pending: 'Pending',
      confirmed: 'Confirmed',
      preparing: 'Preparing',
      ready: 'Ready for Pickup',
      outForDelivery: 'Out for Delivery',
      delivered: 'Delivered',
      cancelled: 'Cancelled',
    },
    rateOrder: 'Rate Your Order',
    rateExperience: 'How was your experience?',
    reviewPlaceholder: 'Share your experience...',
    submitReview: 'Submit Review',
    thankYou: 'Thank you for your review!',
  },

  // Success
  success: {
    title: 'Order Placed!',
    subtitle: "We've received your order and it's being prepared",
    orderNumber: 'Your order number',
    trackOrder: 'Track Order',
    backToHome: 'Back to Home',
    shareOrder: 'Share',
    copyNumber: 'Copy',
    copied: 'Copied!',
  },

  // Profile
  profile: {
    title: 'Profile',
    editProfile: 'Edit Profile',
    addresses: 'My Addresses',
    favorites: 'Favorites',
    settings: 'Settings',
    notifications: 'Notifications',
    switchRestaurant: 'Switch Restaurant',
    helpSupport: 'Help & Support',
    privacyPolicy: 'Privacy Policy',
    termsConditions: 'Terms & Conditions',
    about: 'About',
    version: 'Version',
    noFavorites: 'No favorites yet',
    noFavoritesSubtitle: 'Save items you love for quick access',
  },

  // Address
  address: {
    title: 'Addresses',
    addAddress: 'Add Address',
    editAddress: 'Edit Address',
    home: 'Home',
    work: 'Work',
    other: 'Other',
    streetAddress: 'Street Address',
    city: 'City',
    state: 'State / Province',
    zipCode: 'ZIP / Postal Code',
    country: 'Country',
    instructions: 'Delivery Instructions',
    instructionsPlaceholder: 'E.g. Ring doorbell, Leave at door...',
    setDefault: 'Set as Default',
    deleteAddress: 'Delete Address',
    deleteConfirm: 'Delete this address?',
    noAddresses: 'No addresses saved',
    addFirstAddress: 'Add your first delivery address',
    pickOnMap: 'Pick on map',
    useCurrentLocation: 'Use current location',
  },

  // Settings
  settings: {
    title: 'Settings',
    appearance: 'Appearance',
    language: 'Language',
    notifications: 'Notifications',
    darkMode: 'Dark Mode',
    lightMode: 'Light Mode',
    systemMode: 'System Default',
    pushNotifications: 'Push Notifications',
    orderUpdates: 'Order Updates',
    promotions: 'Promotions & Deals',
    english: 'English',
    urdu: 'اردو',
  },

  // Common
  common: {
    save: 'Save',
    cancel: 'Cancel',
    confirm: 'Confirm',
    delete: 'Delete',
    edit: 'Edit',
    add: 'Add',
    remove: 'Remove',
    close: 'Close',
    done: 'Done',
    back: 'Back',
    next: 'Next',
    skip: 'Skip',
    ok: 'OK',
    yes: 'Yes',
    no: 'No',
    retry: 'Try Again',
    loading: 'Loading...',
    search: 'Search',
    filter: 'Filter',
    sort: 'Sort',
    clear: 'Clear',
    all: 'All',
    or: 'or',
  },

  // Errors
  errors: {
    generic: 'Something went wrong',
    genericSubtitle: 'Please try again',
    network: 'No internet connection',
    networkSubtitle: 'Check your connection and try again',
    timeout: 'Request timed out',
    unauthorized: 'Your session has expired. Please sign in again.',
    forbidden: "You don't have permission to do this",
    notFound: 'This item no longer exists',
    server: 'Server error. Please try again later.',
    orderFailed: 'Failed to place order',
    orderFailedSubtitle: 'Your cart has been saved. Please try again.',
  },

  // Empty states
  empty: {
    cart: 'Your cart is empty',
    cartSubtitle: 'Add items from the menu to get started',
    orders: 'No orders yet',
    ordersSubtitle: 'Your order history will appear here',
    favorites: 'No favorites saved',
    favoritesSubtitle: 'Tap the heart icon on any item to save it',
    addresses: 'No addresses saved',
    addressesSubtitle: 'Add a delivery address to get started',
    search: 'No results found',
    searchSubtitle: 'Try different keywords',
  },
} as const;
