export const UI = {
  // Touch targets
  MIN_TOUCH_SIZE: 44,
  PRIMARY_BUTTON_HEIGHT: 48,

  // Debounce
  SEARCH_DEBOUNCE_MS: 300,
  QUANTITY_DEBOUNCE_MS: 200,

  // Pagination
  PAGE_SIZE: 20,
  INFINITE_THRESHOLD: 0.8,

  // Image
  BLUR_HASH_COMPONENT_X: 4,
  BLUR_HASH_COMPONENT_Y: 3,

  // Limits
  MAX_QUANTITY: 99,
  MAX_ITEM_NOTES_LENGTH: 200,
  MAX_ORDER_NOTES_LENGTH: 500,
  MAX_REVIEW_LENGTH: 500,
  MAX_ADDRESS_INSTRUCTIONS_LENGTH: 200,

  // Animation
  SKELETON_ANIMATION_DURATION: 1200,
  TOAST_AUTO_DISMISS_MS: 3500,
  TOAST_ERROR_DISMISS_MS: 5000,

  // Tab bar
  TAB_BAR_HEIGHT: 64,

  // Header
  HEADER_HEIGHT: 56,
} as const;
